name: 'Tests'

on:
  push:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        laravel: ['10']

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: pcov

    - name: Setup Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests for Local
      run: |
        REPLICATION_MODE=local vendor/bin/phpunit --coverage-text --coverage-clover=coverage_local.xml

    - name: Run tests for Redis
      run: |
        REPLICATION_MODE=redis vendor/bin/phpunit --coverage-text --coverage-clover=coverage_redis.xml

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        file: '*.xml'
        token: ${{ secrets.CODECOV_TOKEN }}
